AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Meloy Judging Portal - Express Monolith API

Parameters:
  RDSSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing RDS credentials
    Default: arn:aws:secretsmanager:us-east-1:271669412379:secret:meloyjudge/rds/credentials-X5m8P7

  JWTSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing JWT signing key
    Default: arn:aws:secretsmanager:us-east-1:271669412379:secret:meloyjudge/jwt/secret-0uBnoy

  CASServiceUrl:
    Type: String
    Description: CAS callback service URL for TAMU authentication
    Default: https://main.dnwd5yr9u60pa.amplifyapp.com/auth/callback

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 512
    Environment:
      Variables:
        RDS_SECRET_ARN: !Ref RDSSecretArn
        JWT_SECRET_ARN: !Ref JWTSecretArn
        CAS_SERVICE_URL: !Ref CASServiceUrl
        NODE_ENV: production
        DEV_MODE: 'true'  # ⚠️ Set to 'false' for production!
    Architectures:
      - x86_64
    VpcConfig:
      SecurityGroupIds:
        - sg-079fd1a5f67dd2d75
      SubnetIds:
        - subnet-037afc317860648be  # us-east-1a (private)
        - subnet-059c9242e7c6e9a0a  # us-east-1b (private)

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref RDSSecretArn
                  - !Ref JWTSecretArn

  # HTTP API Gateway
  MeloyJudgeApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod
      CorsConfiguration:
        AllowOrigins:
          - 'https://main.dnwd5yr9u60pa.amplifyapp.com'
          - 'http://localhost:3000'
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
        MaxAge: 300

  # Single API Function with Express Routing
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: meloy-judge-api
      CodeUri: ./
      Handler: dist/app.handler
      Description: Main API function with Express routing for all endpoints
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        # Catch-all route for Express to handle
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref MeloyJudgeApi
            Path: /{proxy+}
            Method: ANY
        # Health check endpoint
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref MeloyJudgeApi
            Path: /health
            Method: GET
    Metadata:
      BuildMethod: nodejs18.x

Outputs:
  MeloyJudgeApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${MeloyJudgeApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
  
  MeloyJudgeApiId:
    Description: API Gateway ID
    Value: !Ref MeloyJudgeApi
  
  ApiFunctionName:
    Description: Lambda function name
    Value: !Ref ApiFunction
  
  ApiFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt ApiFunction.Arn
